name: CIold
on: 
  workflow_dispatch:
 
jobs:
 node-server-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
         Port: [10011, 10012, 10013, 10014, 10015]
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v2
        name: Server build start on Port ${{matrix.Port}}
      - name: Run the Server build process
        uses: addnab/docker-run-action@v3
        with:
            image: ${{ secrets.IMAGE }}
            run: |
                if [ ${{ matrix.Port }} == "10011" ]; then
                    CKEY="CLIENT_KEY1"
                elif [ ${{ matrix.Port }} == "10012" ]; then
                    CKEY="CLIENT_KEY2"
                elif [ ${{ matrix.Port }} == "10013" ]; then
                    CKEY="CLIENT_KEY3"
                elif [ ${{ matrix.Port }} == "10014" ]; then
                    CKEY="CLIENT_KEY4"
                else
                    CKEY="CLIENT_KEY5"
                fi
                echo "Client Key = $CKEY on Port > ${{ matrix.Port }}"
                pwd
            shell: bash
